Repository Consensys/linea-constraints, pull requests merged in 2024-09, with the labels that each got.

#320 fix(oob): inst modexp pricing f of max
  oob/constraints.lisp
Labels: bug

#328 Removing refunds for `SELDESTRUCT`'s
  hub/constants.lisp
  hub/constraints/generalities/gas.lisp
  hub/constraints/generalities/refunds.lisp
  hub/constraints/heartbeat/ABS_TX_NUM_and_BTC_NUM.lisp
  hub/constraints/instruction-handling/halting/selfdestruct.lisp
  hub/lookups/hub_into_gas.lisp
Labels: bug

#336 fix(exp): use CT_MAX_CMPTN_MODEXP_LOG
  exp/constraints.lisp
Labels: veridise audit

#334 fix(exp): add finalization constraint
  exp/constraints.lisp
Labels: veridise audit

#324 fix(mmu): add missing constraint
  mmu/constraints.lisp
Labels: veridise audit

#351 fix(ecdata): add counter constancy on NOT_ON_G2 and NOT_ON_G2_ACC
  ecdata/constraints.lisp
Labels: veridise audit

#353 fix(exp): remove not necessary computation
  exp/constants.lisp
  exp/constraints.lisp
Labels: veridise audit

#358 fix(exp): index lookups
  exp/constraints.lisp
Labels: veridise audit

#356 fix(rlpTxn): typo for small signature
  rlptxn/constraints.lisp
Labels: bug

#393 Fix: type of `SHB_k_XX` columns
  shf/columns.lisp
Labels: veridise audit

#395 Constraining the `BIT_3` column in the `EXT` module
  alu/ext/constraints.lisp
Labels: bug, veridise audit

#369 fix typo in RLP_TXN phase Beta
  rlptxn/constraints.lisp
Labels: veridise audit

#381 fix(BIN): remove unnecessary preconditions
  bin/constraints.lisp
Labels: veridise audit

#378 fix(txnData): missing constraint
  txndata/constraints.lisp
  txndata/lookups/txndata_into_hub.lispX
Labels: veridise audit

#386 Implementation of `MMIO` update
  Makefile
  mmio/constraints.lisp
  mmio/instructions.lisp
  mmio/patterns.lisp
  mmio/specialized.lisp
Labels: veridise audit

#388 Implementation of `MMU` update
  Makefile
  mmio/constraints.lisp
  mmu/constraints.lisp
  mmu/instructions/any_to_ram_with_padding/common.lisp
  mmu/instructions/any_to_ram_with_padding/pure_padding.lisp
  mmu/instructions/any_to_ram_with_padding/some_data.lisp
  mmu/instructions/blake.lisp
  mmu/instructions/exo_to_ram_transplant.lisp
  mmu/instructions/invalid_code_prefix.lisp
  mmu/instructions/mload.lisp
  mmu/instructions/modexp_data.lisp
  mmu/instructions/modexp_zero.lisp
  mmu/instructions/mstore.lisp
  mmu/instructions/mstore8.lisp
  mmu/instructions/ram_to_exo_with_padding.lisp
  mmu/instructions/ram_to_ram_sans_padding.lisp
  mmu/instructions/right_padded_word_extraction.lisp
Labels: veridise audit

#376 fix(rlprcpt): precondition constraint error
  rlptxrcpt/constraints.lisp
Labels: veridise audit

#365 fix(ROM): missing and duplicate constraint
  rom/constraints.lisp
Labels: veridise audit

#374 fix(blockData): missing finalization constraint
  blockdata/constraints.lisp
Labels: veridise audit

#367 fix(shf): remove unnecessary binary constraint
  shf/columns.lisp
Labels: veridise audit

#371 fix(mmio): missing constraint + typo + overconstrained
  mmio/consistency.lisp
  mmio/constraints.lisp
  mmio/lookups/mmio_into_rlptxn.lisp
  mmio/patterns.lisp
Labels: veridise audit

#403 fix(rlpTxn): constraint ADDR during AccessList tuple & ChainId
  rlptxn/constants.lisp
  rlptxn/constraints.lisp
Labels: bug, veridise audit
