Repository Consensys/linea-constraints, pull requests merged in 2024-10, with the labels that each got.

#415 fix(mxp): add constancy constraints for CN and DEPLOYS
  mxp/constraints.lisp
Labels: veridise audit

#421 Fix for type issues in MUL
  alu/mul/columns.lisp
Labels: bug

#419 Fix value constraints for EXTCODESIZE / EXTCODECOPY
  hub/constraints/instruction-handling/acc.lisp
Labels: veridise audit

#438 Deployment transactions should check more vanishing constraints
  hub/constraints/consistency/account/constraints.lisp
  hub/constraints/tx_init/constraints.lisp
  hub/constraints/tx_skip/constraints.lisp
Labels: veridise audit

#417 fix(constants): correct refund constants
  constants/constants.lisp
Labels: veridise audit

#447 Copy instructions use stack items in the wrong order
  hub/constraints/instruction-handling/copy.lisp
Labels: veridise audit

#445 MSTORE8 wrongly treated as type 2 instruction in STACKRAM instruction family
  hub/constraints/generalities/auxiliary_stamps.lisp
  hub/constraints/instruction-handling/stack_ram.lisp
Labels: veridise audit

#435 Lookup selector's for `gas-into-wcp` hadn't been updated
  gas/lookups/gas-into-wcp.lisp
Labels: bug

#433 Createe reverts with child (itself, that is)
  hub/constraints/instruction-handling/create/constraints/deployment-failures.lisp
Labels: veridise audit

#451 Add `GAS_LIMIT` to `HUB -> TXN_DATA` lookup
  hub/lookups/hub_into_txn_data.lisp
Labels: veridise audit

#443 delete size into nBytes in the lookup mmio into rom
  mmio/lookups/mmio_into_rom.lisp
Labels: bug

#453 Re-introduction of generic constraints for `HEIGHT_NEW` and `HEIGHT` in relation to `ALPHA` and `DELTA`
  hub/constraints/generalities/stack_height.lisp
  hub/constraints/heartbeat/constancy_conditions.lisp
  hub/constraints/stack_patterns.lisp
Labels: veridise audit

#449 RETURNDATACOPY must always load the current execution context
  Makefile
  gas/columns.lisp
  hub/constraints/instruction-handling/copy.lisp
  hub/constraints/instruction-handling/copy/calldatacopy.lisp
  hub/constraints/instruction-handling/copy/codecopy.lisp
  hub/constraints/instruction-handling/copy/extcodecopy.lisp
  hub/constraints/instruction-handling/copy/generalities.lisp
  hub/constraints/instruction-handling/copy/returndatacopy.lisp
  hub/lookups/hub_into_gas.lisp
Labels: veridise audit

#439 fix: add CFI to the lookup txnData into rlpTxn
  txndata/lookups/txndata_into_rlptxn.lisp
Labels: bug, veridise audit

#455 Using `stack/STATIC_GAS` rather than `GAS_CONST_G_SELFDESTRUCT`
  hub/constraints/instruction-handling/halting/selfdestruct.lisp
Labels: enhancement

#457 Constraints update for GAS columns generalities
  hub/constraints/generalities/gas.lisp
Labels: veridise audit

#458 No longer impose vanishing of GAS_COST in case of nonOogException
  hub/constraints/generalities/gas.lisp
Labels: veridise audit

#464 Make `HEIGHT` and `HEIGHT_NEW` explicitly `hub-stamp-constant`
  hub/constraints/generalities/stack_height.lisp
Labels: bug, veridise audit

#462 Typo and bug fixes for the `ACC` instruction family
  hub/constraints/instruction-handling/acc.lisp
Labels: bug, veridise audit

#469 Implementation of HUB / MXP interface bugfix
  hub/columns/miscellaneous.lisp
  hub/constraints/instruction-handling/call/shorthands.lisp
  hub/constraints/instruction-handling/call/specialized/initialize_callee_context.lisp
  hub/constraints/instruction-handling/call/specialized/precompile-scenario-row-setting-for-precompiles.lisp
  hub/constraints/instruction-handling/halting/return.lisp
  hub/constraints/instruction-handling/halting/revert.lisp
  hub/constraints/instruction-handling/halting/selfdestruct.lisp
  hub/constraints/instruction-handling/halting/shorthands.lisp
  hub/constraints/instruction-handling/halting/stop.lisp
  hub/lookups/hub_into_mxp.lisp
  mxp/columns.lisp
  mxp/constraints.lisp
Labels: bug

#466 Specification glitches
  alu/mul/constraints.lisp
  exp/columns.lisp
  exp/constraints.lisp
  hub/columns/shared.lisp
  hub/columns/stack.lisp
  hub/constraints/account-rows/specialized.lisp
  hub/constraints/consistency/account/constraints.lisp
  hub/constraints/consistency/stack/constraints.lisp
  hub/constraints/consistency/storage/constraints.lisp
  hub/constraints/context.lisp
  hub/constraints/generalities/auxiliary_stamps.lisp
  hub/constraints/generalities/context.lisp
  hub/constraints/generalities/exceptions.lisp
  hub/constraints/heartbeat/constancy_conditions.lisp
  hub/constraints/heartbeat/hub_stamp.lisp
  hub/constraints/instruction-handling/acc.lisp
  hub/constraints/instruction-handling/call/generalities/1st_set_of_account_rows.lisp
  hub/constraints/instruction-handling/call/generalities/universal.lisp
  hub/constraints/instruction-handling/call/precompiles/blake/generalities.lisp
  hub/constraints/instruction-handling/call/precompiles/blake/surviving_the_hub.lisp
  hub/constraints/instruction-handling/call/precompiles/common/generalities.lisp
  hub/constraints/instruction-handling/call/precompiles/modexp/common.lisp
  hub/constraints/instruction-handling/call/precompiles/modexp/success.lisp
  hub/constraints/instruction-handling/call/specialized/missing-context-parameters.lisp
  hub/constraints/instruction-handling/con.lisp
  hub/constraints/instruction-handling/copy/calldatacopy.lisp
  hub/constraints/instruction-handling/copy/codecopy.lisp
  hub/constraints/instruction-handling/copy/extcodecopy.lisp
  hub/constraints/instruction-handling/copy/generalities.lisp
  hub/constraints/instruction-handling/copy/returndatacopy.lisp
  hub/constraints/instruction-handling/create/constraints/generalities.lisp
  hub/constraints/instruction-handling/create/constraints/unaborted.lisp
  hub/constraints/instruction-handling/create/standpoint.lisp
  hub/constraints/instruction-handling/halting/return.lisp
  hub/constraints/instruction-handling/halting/revert.lisp
  hub/constraints/instruction-handling/halting/selfdestruct.lisp
  hub/constraints/instruction-handling/invalid.lisp
  hub/constraints/instruction-handling/jump.lisp
  hub/constraints/instruction-handling/keccak.lisp
  hub/constraints/instruction-handling/log.lisp
  hub/constraints/instruction-handling/machine_state.lisp
  hub/constraints/instruction-handling/stack_ram.lisp
  hub/constraints/instruction-handling/sto.lisp
  hub/constraints/miscellaneous-rows/mmu.lisp
  hub/constraints/miscellaneous-rows/oob.lisp
  hub/constraints/miscellaneous-rows/weighted_misc_flag_sum.lisp
  hub/constraints/scenario-rows/shorthands/selfdestruct.lisp
  hub/constraints/tx_prewarm/constraints.lisp
  hub/constraints/tx_skip/constraints.lisp
  hub/lookups/hub_into_gas.lisp
  hub/lookups/hub_into_rom_lex.lisp
  mmio/lookups/mmio_into_kec.lisp
  mmio/lookups/mmio_into_kec.lispX
  mmio/lookups/mmio_into_ripsha.lisp
  mmio/lookups/mmio_into_ripsha.lispX
  rlptxn/lookups/rlp_txn_into_hub.lispX
  trm/columns.lisp
Labels: bug, veridise audit

#473 homogenize lookups rlptxn <-> hub
  hub/lookups/hub_into_rlp_txn.lisp
  rlptxn/lookups/rlp_txn_into_hub.lispX
Labels: veridise audit

#475 typo
  rlptxn/constraints.lisp
Labels: veridise audit

#477 More Veridise debugging
  Makefile
  hub/constraints/consistency/stack/columns.lisp
  hub/constraints/generalities/context.lisp
  hub/lookups/hub_into_rlp_txn.lisp
  logdata/constraints.lisp
  loginfo/lookups/loginfo-into-hub.lisp
  loginfo/lookups/loginfo-into-logdata.lisp
  loginfo/lookups/loginfo-into-rlprcpt.lisp
Labels: veridise audit

#471 delete duplicate constraint
  alu/mod/columns.lisp
  alu/mod/constraints.lisp
  alu/mul/constraints.lisp
  ecdata/constraints.lisp
  exp/constraints.lisp
  gas/constraints.lisp
  hub/columns/shared.lisp
  hub/constraints/consistency/account/constraints.lisp
  hub/constraints/heartbeat/peeking_flags.lisp
  hub/constraints/tx_skip/constraints.lisp
  logdata/lookups/logdata-to-rlprcpt.lisp
  mmu/constraints.lisp
  mxp/constraints.lisp
  oob/constraints.lisp
  shakiradata/constraints.lisp
  txndata/constraints.lisp
  wcp/constraints.lisp
Labels: veridise audit

#489 Duplicate and unused code snippets EXP OOB MXP
  exp/constraints.lisp
  oob/constraints.lisp
  wcp/constraints.lisp
Labels: veridise audit
